name: radio_qth_map
description: qth map for amature/free ham
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.1
  responsive_framework: ^1.1.1
  latlong2: ^0.9.0
  provider: ^6.1.1
  flutter_map: ^6.0.1
  url_launcher: ^6.2.1
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.0
  flutter_svg: ^2.0.9
  go_router: ^14.0.0
  google_fonts: ^6.1.0
  dart_adif:
    git:
      url: https://github.com/numa08/dart_adif.git
      ref: fe2a6a0f5c883e7e09e1d65e6c928b3cc10982a9
  file_picker: ^8.0.0
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.17.4
  email_validator: ^2.1.17
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - image/
    - key.env
